package ch.heigvd.amt.movie.api.endpoints;

import ch.heigvd.amt.movie.api.model.Movie;
import ch.heigvd.amt.movie.entities.MovieEntity;
import ch.heigvd.amt.movie.repositories.MovieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;

import java.util.ArrayList;
import java.util.List;

/**
 * Sptring controller that implements all operations generated by codegen
 * @author Gilliand Loris
 * @author Tutic Mateo
 * @version 1.0
 * @since 11.12.2019
 */
@Controller
public class MoviesApiController implements  MoviesApi {
    @Autowired
    MovieRepository movieRepository;

    public ResponseEntity<List<Movie>> getMovies() {
        List<Movie> movies = new ArrayList<>();
        for (MovieEntity movieEntity : movieRepository.findAll()) {
            movies.add(toMovie(movieEntity));
        }
        return ResponseEntity.ok(movies);
    }

    private Movie toMovie(MovieEntity entity) {
        Movie movie = new Movie();
        movie.setTitle(entity.getTitle());
        movie.setYear(entity.getYear());
        return movie;
    }
}
