package ch.heigvd.amt.auth.api.endpoints;

import ch.heigvd.amt.auth.api.model.User;
import ch.heigvd.amt.auth.api.util.AuthUtils;
import ch.heigvd.amt.auth.entites.UserEntity;
import ch.heigvd.amt.auth.repositories.UserRepository;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiParam;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import javax.validation.Valid;
import java.net.URI;

/**
 * Spring controller that implements all operations generated by codegen
 * @author Gilliand Loris
 * @author Tutic Mateo
 * @version 1.0
 * @since 11.12.2019
 */
@Controller
@Api(tags = "admin")
public class RegistrationApiController implements RegistrationApi {
    @Autowired
    UserRepository userRepository;

    public ResponseEntity<Void> createUser(@ApiParam(value = "", required = true) @Valid @RequestBody User user) {
        UserEntity newUserEntity = toUserEntity(user);
        userRepository.save(newUserEntity);

        URI location = ServletUriComponentsBuilder
                .fromCurrentRequest().replacePath("users/${id}")
                .buildAndExpand(newUserEntity.getId()).toUri();
        return ResponseEntity.created(location).build();
    }

    private UserEntity toUserEntity(User user) {
        UserEntity entity = new UserEntity();
        entity.setEmail(user.getEmail());
        entity.setLastname(user.getLastname());
        entity.setFirstname(user.getFirstname());
        entity.setPassword(AuthUtils.hashPassword(user.getPassword()));
        return entity;
    }
}
