package ch.heigvd.amt.auth.api.endpoints;

import ch.heigvd.amt.auth.api.model.Credentials;
import ch.heigvd.amt.auth.api.util.AuthUtils;
import ch.heigvd.amt.auth.entites.UserEntity;
import ch.heigvd.amt.auth.repositories.UserRepository;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiParam;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;

/**
 * Spring controller that implements all operations generated by codegen
 * @author Gilliand Loris
 * @author Tutic Mateo
 * @version 1.0
 * @since 11.12.2019
 */
@Controller
@Api(tags = "session")
public class SessionApiController implements SessionApi {
    @Autowired
    UserRepository userRepository;

    public ResponseEntity<String> getJWTToken(@ApiParam(value = "", required = true) @Valid @RequestBody Credentials credentials) {
        UserEntity user = userRepository.findByEmail(credentials.getEmail());

        // Check user credentials
        if (!user.getPassword().equals(credentials.getPassword())) {
            throw new IllegalArgumentException("The password is wrong");
        }

        try {
            String jwtToken = AuthUtils.createJWTString(user.getId(), user.isAdmin());
            return ResponseEntity.ok(jwtToken);
        } catch (IllegalArgumentException e) {
            return ResponseEntity.status(401).body(e.getMessage());
        }
    }
}
