[global]
  sendAnonymousUsage = false

# Get dynamic configuration from Docker
[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

# Listen on those ports for incoming requests
[entryPoints]
  [entryPoints.web]
    address = ":80"

# Configure Traefik api
[api]
  insecure = true
  dashboard = true
  debug = true

# Configure logs and metrics
[log]
  level = "DEBUG"
  format = "common"