TRUNCATE TABLE user;
INSERT INTO user (lastname, firstname, email, password) VALUES ("Gwenny", "Albon", "galbon0@weibo.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Candida", "Kirgan", "ckirgan1@apple.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Brett", "Fuggles", "bfuggles2@cbc.ca", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Ulysses", "Tourry", "utourry3@xing.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Latrena", "Croxon", "lcroxon4@dion.ne.jp", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Riane", "Shord", "rshord5@feedburner.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Bambi", "Scandred", "bscandred6@timesonline.co.uk", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Marget", "MacTrustie", "mmactrustie7@phoca.cz", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Daniella", "Binder", "dbinder8@yale.edu", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Irena", "Yegorkov", "iyegorkov9@chronoengine.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Bobbie", "Glidden", "bgliddena@who.int", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Flossy", "Hyder", "fhyderb@archive.org", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Elfrieda", "Gidney", "egidneyc@ning.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Britney", "Domke", "bdomked@huffingtonpost.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Hugues", "Whye", "hwhyee@imgur.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Sinclair", "Dominguez", "sdominguezf@abc.net.au", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Temp", "Wraggs", "twraggsg@ebay.com", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Hugo", "Cotterrill", "hcotterrillh@icio.us", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Bren", "Badman", "bbadmani@state.tx.us", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password) VALUES ("Melitta", "Dunstone", "mdunstonej@nasa.gov", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");
INSERT INTO user (lastname, firstname, email, password, is_admin) VALUES ("Dupont", "Jean", "admin@admin.ch", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy", 1);
INSERT INTO user (lastname, firstname, email, password) VALUES ("Reis", "Mark", "notadmin@admin.ch", "$2a$10$db71I3CbNntNS0JqaGNI9OMRawCfuQJJf6oTDBLlYuMiWhdZ6Fxpy");