INSERT INTO movie (title, year) VALUES ("﻿Aogura", "2006");
INSERT INTO movie (title, year) VALUES ("Aoi firumu: Shinasadame", "1968");
INSERT INTO movie (title, year) VALUES ("Aoi hate", "1955");
INSERT INTO movie (title, year) VALUES ("Aoi kemono: hisokana tanoshimi", "1978");
INSERT INTO movie (title, year) VALUES ("Aoi kisetuf?", "1987");
INSERT INTO movie (title, year) VALUES ("Aoi Misaki wa yoru mieru", "2002");
INSERT INTO movie (title, year) VALUES ("Aoi no abarembo", "1961");
INSERT INTO movie (title, year) VALUES ("Aoi sanmyaku", "1949");
INSERT INTO movie (title, year) VALUES ("Aoi sanmyaku", "1963");
INSERT INTO movie (title, year) VALUES ("Aoi sanmyaku '88", "1988");
INSERT INTO movie (title, year) VALUES ("Aoi shinju", "1951");
INSERT INTO movie (title, year) VALUES ("Aoi taiken: Kashin no itami", "1984");
INSERT INTO movie (title, year) VALUES ("Aoi uta - Nodo jiman Seishun hen", "2006");
INSERT INTO movie (title, year) VALUES ("Aolei Yilan", "1979");
INSERT INTO movie (title, year) VALUES ("Aoom", "1970");
INSERT INTO movie (title, year) VALUES ("Aos Mortos da Grande Guerra", "1933");
INSERT INTO movie (title, year) VALUES ("Aouchtam", "1996");
INSERT INTO movie (title, year) VALUES ("Aozora", "1989");
INSERT INTO movie (title, year) VALUES ("Aozora kÃ´kyÃ´gaku", "1943");
INSERT INTO movie (title, year) VALUES ("Aozora samba-garasu", "1934");